const { auth, resolver } = require("@iden3/js-iden3-auth");
const getRawBody = require("raw-body");
const asyncFunction = require("../utils/asyncCatch");
const { GenderCredential } = require("../utils/proofRequest");
const path = require("path");
const { v4: uuidv4 } = require("uuid");

// ================ UTILS ====================
const authRequests = new Map();
const sessionExpirations = new Map();

const STATUS = {
  IN_PROGRESS: "IN_PROGRESS",
  ERROR: "ERROR",
  DONE: "DONE",
};

const socketMessage = (fn, status, data) => ({
  fn,
  status,
  data,
});
// ========================== UTILS  =====================

// =========================== CONTROLLER FOR GENDER VERIFICATION GET QR CODE ==============================
const getGenderVerificationdQR = (wss) =>
  asyncFunction((req, res) => {
    // #swagger.tags = ['age verificaion']
    const sessionId = req.query.sessionId ?? uuidv4();
    console.log("getAuthQr for", sessionId);

    wss.emit(
      sessionId,
      socketMessage("getAuthQr", STATUS.IN_PROGRESS, sessionId)
    );

    const uri = `${process.env.HOSTED_SERVER_URL}/gender-verification/callback?sessionId=${sessionId}`;

    const request = {
      id: sessionId,
      thid: sessionId,
      from: "did:polygonid:polygon:mumbai:2qDyy1kEo2AYcP3RT4XGea7BtxsY285szg6yP9SPrs",
      typ: "application/iden3comm-plain-json",
      type: "https://iden3-communication.io/authorization/1.0/request",
      body: {
        reason: "Must be born before this year",
        callbackUrl: uri,
        scope: [GenderCredential()],
      },
    };

    authRequests.set(sessionId, request);

    // Set a timer to expire the session after 5 minutes
    const sessionTimer = setTimeout(() => {
      if (authRequests.has(sessionId)) {
        authRequests.delete(sessionId);
        sessionExpirations.delete(sessionId);
        console.log("Session expired:", sessionId);
      }
    }, 0.25 * 60 * 1000);

    sessionExpirations.set(sessionId, sessionTimer);

    wss.emit(sessionId, socketMessage("getAuthQr", STATUS.DONE, request));

    return res.status(200).json(request);
  });
// =========================== CONTROLLER FOR GENDER VERIFICATION GET QR CODE ==============================

// ====================== CONTROLLER FOR GENDER VERIFICATION CALLBACK =======================================
const genderVerificationCallback = (wss) =>
  asyncFunction(async (req, res) => {
    // #swagger.tags = ['age verificaion']
    const sessionId = req.query.sessionId;

    console.log(authRequests.keys());
    // get this session's auth request for verification
    const authRequest = authRequests.get(sessionId);

    authRequests.delete(sessionId);
    sessionExpirations.delete(sessionId);
    console.log(`handleVerification for ${sessionId}`);

    wss.emit(
      sessionId,
      socketMessage("handleVerification", STATUS.IN_PROGRESS, authRequest)
    );

    // get JWZ token params from the post request
    const raw = await getRawBody(req);
    const tokenStr = raw.toString().trim();

    // The CredentialAtomicQuerySigValidator contract is used to verify any credential-related zk proof
    // generated by the user using the credentialAtomicQuerySigV2OnChain circuit.
    // https://0xpolygonid.github.io/tutorials/contracts/overview/#blockchain-addresses
    const mumbaiContractAddress = "0x134B1BE34911E39A8397ec6289782989729807a4";
    const keyDIR = "../keys";

    const ethStateResolver = new resolver.EthStateResolver(
      process.env.RPC_URL_MUMBAI,
      mumbaiContractAddress
    );

    const resolvers = {
      ["polygon:mumbai"]: ethStateResolver,
    };

    const verifier = await auth.Verifier.newVerifier({
      stateResolver: resolvers,
      circuitsDir: path.join(__dirname, keyDIR),
      ipfsGatewayURL: "https://ipfs.io",
    });

    try {
      const opts = {
        AcceptedStateTransitionDelay: 5 * 60 * 1000, // up to a 5 minute delay accepted by the Verifier
      };
      const authResponse = await verifier.fullVerify(
        tokenStr,
        authRequest,
        opts
      );
      const userId = authResponse.from;

      wss.emit(
        sessionId,
        socketMessage("handleVerification", STATUS.DONE, authResponse)
      );

      console.log(JSON.stringify(authResponse));

      await postAgeVerification(sessionId, tokenStr);

      return res
        .status(200)
        .set("content-type", "application/json")
        .send("User" + userId + "successfully authenticated");
    } catch (error) {
      console.log(error);

      wss.emit(
        sessionId,
        socketMessage("handleVerification", STATUS.ERROR, error)
      );

      return res.status(500).send(error);
    }
  });

// post the session id, jwz and token body for age verification to the dyneum server
const postAgeVerification = async (sessionId, jwz) => {
  const url = `${process.env.DYNEUM_SERVER}/api/v1/auth/age-verification-callback/`;
  const data = {
    jwz: jwz,
    session_id: sessionId,
  };

  try {
    const res = await fetch(url, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        accept: "application/json",
      },
      body: JSON.stringify(data),
    });

    await res.json();
  } catch (err) {
    console.log(err);
  }
};
// ==================== CONTROLLER FOR GENDER VERIFICATION CALLBACK ===========================

module.exports = {
  getGenderVerificationdQR,
  genderVerificationCallback,
};
